// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvhbkjwjwqtmasfparun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2aGJrandqd3F0bWFzZnBhcnVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MjAzNzgsImV4cCI6MjA2MTQ5NjM3OH0.VMUezMFsjNNX2NIxr5u5Se61dn4qKQl_Jqb_5VSccBg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);